# Generated by Django 3.0.4 on 2020-03-19 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200318_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='minion.jpeg', upload_to='profile_pics'),
        ),
    ]
